import Head from "next/head";
import React from "react";
import { useSession, signOut } from "next-auth/react";

import cn from "../../lib/class-name";
import { Component } from "../../types/component";

import Navigation from "../Navigation/Navigation";

export interface Props extends Component {
  children: React.ReactNode;
}

const Layout = ({ children, classNames = [] }: Props) => {
  const { data: session, status } = useSession();

  const logoutHandler = () => {
    signOut();
  };

  return (
    <div className={cn("Layout", [], classNames)}>
      <Head>
        <title>Berichte</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navigation session={session} onClick={logoutHandler} />
      </header>

      <main>{children}</main>
    </div>
  );
};

export default Layout;
